[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
console_error_panic_hook = "0.1.7"
eyre = "0.6.12"
js-sys = "0.3.77"
leptoaster = "0.2.3"
leptos = { version = "0.8.2", features = ["csr"] }
leptos-use = { version = "0.15.7", features = ["on_click_outside"] }
leptos_meta = "0.8.2"
leptos_router = "0.8.2"
leptos_toaster = "0.2.0"
reqwest = { version = "0.12.19", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"

[lib]
name = "hotel"
path = "src/lib.rs"
